[package]
name = "tiny"
version = "0.4.5"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
repository = "https://github.com/osa1/tiny"
readme = "README.md"
license = "MIT"
keywords = ["irc"]
categories = ["network-programming"]
description = "An IRC client"
edition = "2018"

[badges]
travis-ci = { repository = "osa1/tiny" }

[[bin]]
name = "tiny"
path = "src/main.rs"

[dependencies]
base64 = "0.6.0"
dirs = "1.0.2"
libc = "0.2.22"
mio = "0.6.9"
native-tls = "0.2.2"
net2 = "0.2.23"
serde = { version = "1.0.8", features = ["derive"] }
serde_yaml = "0.7.1"
take_mut = "0.2.0"
term_input = { path = "term_input", version = "0.1.5" }
time = "0.1"

libtiny_tui = { path = "libtiny_tui" }

[dev-dependencies]
quickcheck = "0.3"

[profile.release]
lto = true
