[package]
name = "libtiny_tui"
version = "0.4.5"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
repository = "https://github.com/osa1/tiny"
readme = "README.md"
license = "MIT"
keywords = ["irc"]
categories = ["network-programming"]
description = "An IRC client"
edition = "2018"

[badges]
travis-ci = { repository = "osa1/tiny" }

[lib]
name = "libtiny_tui"
path = "src/lib.rs"

[dependencies]
futures-util-preview = "0.3.0-alpha.18"
libtiny_ui = { path = "../libtiny_ui" }
notify-rust = "3"
serde = { version = "1.0.8", features = ["derive"] }
tempfile = "3.0.3"
term_input = { path = "../term_input" }
termbox_simple = { path = "../termbox", version = "0.2.3" }
time = "0.1"
tokio = { git = "https://github.com/tokio-rs/tokio.git", features = ["timer"] }

[dev-dependencies]
mio = "0.6.9"
libc = "0.2.22"
